### ISSUE TITLE
Black rectangle partially covering neural data

### ISSUE THREAD

**Issue by SamMinkowicz** [neuroethology/bento#126]
Hi, when viewing neural data in Bento there is a black rectangle that mostly covers the last trace. There should be 3 traces visible in the photo below.

Thanks for your help!

![bento_neural_data_box](https://user-images.githubusercontent.com/42850123/160007936-8e36561e-1df4-4794-b524-b98d18cb3269.png)

**Comment by annkennedy** [comment]
Addl detail- this is in Windows, we've never tested Bento with this few traces before so I'm guessing this is because the vertical extent of the neural data plot is less than that of the widget?

**Comment by annkennedy** [comment]
Fixed in bug/fix neural view scaling and merged into Develop
