### ISSUE TITLE
Two empty views/plots appear in the neural data window when changing timescale

### ISSUE THREAD

**Issue by SamMinkowicz** [neuroethology/bento#128]
Hi, two new views/plots appear in the neural data view when I hold shift and drag in or out to change the timescale. The two extra views disappear when I change the size of the screen.

This is on Windows with Bento version 0.1.1-beta

See the video below.

Thanks for your help!

https://user-images.githubusercontent.com/42850123/160009230-3bfbfd2a-9e1c-4747-ad65-7646e1b36c37.mp4

**Comment by annkennedy** [comment]
Fixed in bug/fix neural view scaling and merged into Develop.
