### ISSUE TITLE
Annotations plug-in

### ISSUE THREAD

**Issue by daverumph** [neuroethology/bento#150]
Support import of annotations in various TBD formats

- current annotations loading refactored as plug-in instance
- display and manipulation of annotations unchanged -- core bento functionality
- saving of annotations unchanged -- core bento functionality

**Comment by annkennedy** [comment]
Addressed and merged into Develop, now supports bento, caltech, boris, simba.
annotation parsing is handled in annot/annot.py. currently somewhat hardcoded so extending it to support other annotation formats isn't quite as trivial as contributing a new plugin for pose. consider taking this implementation and refactoring it to resemble our pose annotation support at some point in the future.
