### ISSUE TITLE
Data Export Support

### ISSUE THREAD

**Issue by daverumph** [neuroethology/bento#154]
Enable people to write standalone data analysis code like Behavior-Triggered Averages

Generic export of data capability

Loop through widgets, asking each to export their data
Use a generic data format (h5 a la neurodata without borders)
Initially save-to-file, but maybe later support passing of "blob" to user-supplied function/module

Prerequisite: consolidate widgets

**Comment by venus-sherathiya** [comment]
data export is supported now
