### ISSUE TITLE
Traces of neural activity should be re-orderable

### ISSUE THREAD

**Issue by annkennedy** [neuroethology/bento#158]
Possible implementation: each neuron has a trace (a QPainterPath) and a row in the heatmap. We want to be able to change the y-axis values for each trace, and re-order the rows of the heatmap, given a provided ordering of the neurons. (This ordering will come from a plugin, like k-means clustering or PCA.)

**Comment by annkennedy** [comment]
We also need a way to show/hide neurons that doesn't lose access to those neurons. Eg a function makeHeatmap(matrix,order) where `matrix` is a 2darray of the data and `order` is the order that rows are plotted (with a -1 for rows that are hidden.)

If we apply a new order, ideally that should be with respect to the current displayed order rather than the original, though that gets a bit tricker.

**Comment by venus-sherathiya** [comment]
It was addressed through enhancement/neuralTracesReordering branch
