### ISSUE TITLE
Neural traces and annotations may not be correctly synchronized

### ISSUE THREAD

**Issue by daverumph** [neuroethology/bento#161]
Need to check, especially if there are nonzero offsets in the data start times.

Also verify behavior in the face of sample-rate differences.

**Comment by annkennedy** [comment]
Here is a file to test with. It has three neurons, whose activity is zero everywhere except on frames 118, 218, and 318.

[test_data.zip](https://github.com/neuroethology/bento/files/8894569/test_data.zip)

**Comment by venus-sherathiya** [comment]
this works fine !!
