### ISSUE TITLE
"Caught Exception No module named 'MySQLdb'.  Probably config data invalid" error

### ISSUE THREAD

**Issue by ellamcho** [neuroethology/bento#168]
Hi! Every time I try to launch the bento python file using the command "python src/bento.py", I get an error that says "Caught Exception No module named 'MySQLdb'.  Probably config data invalid". Is there any way to resolve this? Thanks!

**Comment by venus-sherathiya** [comment]
Which operating system does your machine have ?
Also, are you activating conda environment before "python src/bento.py" ?

**Comment by ellamcho** [comment]
> Which operating system does your machine have ? Also, are you activating conda environment before "python src/bento.py" ?

Hi, my machine is using MacOS and an M1 chip. And yes, I activate my conda environment before calling "python src/bento.py"!

**Comment by venus-sherathiya** [comment]
I just created a new conda environment and launched bento. It works fine with me. I have MacOS with an M1 chip as well. Your conda environment was setup properly, right ?
Try removing the conda environment and create an environment again -- maybe it will work.
If not, please send the screenshot of an error. Thank you !!

**Comment by venus-sherathiya** [comment]
Just to make sure, you are trying to setup the conda environment using bento_mac.yml file and not requirements.txt file, right ?

**Comment by jverpeut** [comment]
I also ran into this problem. I am using a windows machine. The first time it installed ok and I tried to set-up a shared configuration. I received the error "config data invalid. no module named 'mysqldb'.  I deleted everything and tried to reinstall, but I am receiving the same error message. I also received an error message about a color text file, but that I was able to locate and add to the proper location. I am going to try a different version, but wanted to report the error.

![Screenshot 2024-03-06 203432](https://github.com/neuroethology/bento/assets/33037471/72f8d495-9421-410a-8eac-50014cb4e8cd)

![image](https://github.com/neuroethology/bento/assets/33037471/b32acdad-2ffb-43ce-b18a-b8cc983739c4)

**Comment by jverpeut** [comment]
I found that if I delete the config.json file in my users python .bento file that I can reset the installation.

**Comment by venus-sherathiya** [comment]
Can you please try the following ?

1)  First, uninstall your conda environment using `conda remove --bento --all` 
2) Please download the code from this [branch](https://github.com/neuroethology/bento/tree/bug/newEnvironmentFile) 
3) Create a conda environment following the instructions provided in the documentation folder. 

Please let me know if it works or not.

**Comment by jverpeut** [comment]
Yes that worked. Thank you!
