### ISSUE TITLE
tick marks in plots of neural data should adjust when data is scaled

### ISSUE THREAD

**Issue by annkennedy** [neuroethology/bento#39]
Currently tick marks are fixed at 1s intervals, which creates a lot of clutter when the view is zoomed out. There are also multiple rows of ticks, which is a bit distracting- it should be fine to just show tickmarks along the bottom of the neural activity plot.

**Comment by daverumph** [comment]
Also fix the bug where the horizontal scale can go negative, resulting in the neural data running backwards.

**Comment by annkennedy** [comment]
Backwards time is fixed!

Idea for implementation: if user changes the horizontal scale, then once they release the mouse button re-calculate what the tickmarks should be (see if there's any existing code to do this prettily)
Also tickmarks will need (relative) numeric labels for this to work.
